<!DOCTYPE>
<html>
<head>
	<title>
		BARCELONA FC
	</title>
</head>
<body>
<p>El Fútbol Club Barcelona (en catalán, Futbol Club Barcelona) es una entidad polideportiva de Barcelona (España). Fue fundado como club de fútbol el 29 de noviembre de 1899.8​

Una de las principales características del F. C. Barcelona es su carácter polideportivo. Se distingue de las demás instituciones deportivas por el hecho de que posee un extenso palmarés a nivel europeo, por el alto nivel de formación de sus jugadores, el potencial económico que maneja, por la calidad de los jugadores y <br>también porque «posee una remarcable cultura del juego y del triunfo».9​ Asimismo, los medallistas olímpicos que han representado a la entidad blaugrana han conquistado 11 oros, 23 de platas y 28 bronces en las distintas disciplinas deportivas.10​ Además de su sección principal, la de fútbol, el club cuenta con otras <br>cuatro secciones profesionales: las de baloncesto, balonmano, hockey sobre patines y fútbol sala.11​ Entre las cinco secciones profesionales, el F. C. Barcelona suma 39 Ligas de Campeones (o Euroligas en el caso del baloncesto)nota 1​ lo cual le convierte en el segundo club polideportivo más laureado de Europa y, junto a Dinamo de Moscú y CSKA de Moscú (este con 7), el único que ha conseguido el máximo título continental en 5 deportes diferentes.17​<br>

Uno de los datos relevantes del club fue la consecución de la Liga de Campeones consecutivamente durante 17 años, desde la temporada 1995/96 hasta la 2011/12 con alguna de sus secciones profesionales,18​ además ha ganado un «triplete» europeo con las secciones de Fútbol, Balonmano y Hockey Patines en la temporada 2014/15 y 6 «dobletes» europeos con las secciones de Balonmano y Hockey Patines en las temporadas 1996/97, 1999/00 y 2004/05 con las secciones de Baloncesto y Hockey Patines en la temporada 2009/10, con las secciones de Fútbol y Balonmano en la temporada 2010/11 y con las secciones de Fútbol Sala y Hockey Patines en la temporada <br>2013/14.nota 2​ Destaca también el hecho que desde la temporada 1988/89 que se inicia con la victoria del equipo de fútbol, en la final de la Recopa de Europa en Berna contra la Sampdoria hasta la 2011/12, cada temporada durante 24 años, alguno de los deportes del club levantó algún título europeo.nota 3​ En cuanto a temporadas se refiere, en el cómputo global de títulos conseguidos por todas las secciones sin contar los regionales, la temporada 2011-12 fue la más exitosa del club ya que logró la conquista de 17 campeonatos (récord histórico para el club),19​20​ seguido de la temporada 2010-11 con 14 y la 2009-10 con 13.nota 4​21​<br>

Además de estas cinco secciones profesionales, el club cuenta con secciones amateurs en otras disciplinas deportivas: hockey sobre hierba masculino y femenino, atletismo masculino y femenino, patinaje masculino y femenino, hockey sobre hielo, voleibol masculino y femenino, rugby, fútbol playa, fútbol indoor, fútbol <br>femenino y baloncesto en silla de ruedas.11​

Otro de sus hechos distintivos es su masa social de socios y aficionados. El club ha logrado integrar de forma estratégica cuestiones políticas, religiosas, culturales y sociales, que van enmarcadas dentro del ámbito deportivo, esto permite que los socios y los aficionados respondan a todos los eventos sociales del club, también que tengan mayor participación en actividades administrativas y se fortalezcan los vínculos entre las peñas.22​ En 2011 alcanzó los 180 000 <br>socios,nota 5​23​24​ siendo hasta ese momento el segundo equipo con más asociados del mundo (en el primero se situaba el SL Benfica), seguido por el Manchester <br>United.25​ Existen, además, más de 1200 peñas barcelonistas repartidas por todo el mundo.26​27​ El F. C. Barcelona es uno de los cuatro clubes profesionales de España (junto a Real Madrid, Athletic Club y Osasuna) que no es sociedad anónima, de manera que la propiedad del club recae en sus socios.</p>
</body>
</html>